[package]
name = "day-04"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
nom = "7.1.3"
utils = { path = "../utils", version = "*" }
